CREATE TABLE clubs(
ID INTEGER NOT NULL 
    GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
NOMBRE VARCHAR(20),
DESCRIPCION VARCHAR(1000)
)

ALTER TABLE CLUBS ADD PRIMARY KEY(ID)

INSERT INTO CLUBS(NOMBRE) VALUES ('Computación')

SELECT * FROM clubs;